platform :ios, '12.0'

def private_frameworksCommon
  use_frameworks!

  pod 'MBCommon', :path => 'DevPods/MBCommon'
  pod 'MBCommonUI', :path => 'DevPods/MBCommonUI'
  pod 'SBNetworking', :path => 'DevPods/SBNetworking'
  pod 'SBServices', :path => 'DevPods/SBServices'
end

target 'MMDraft' do
  use_frameworks!

  private_frameworksCommon

  pod 'R.swift'
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'ViewAnimator'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
